name: taboo-ai-release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Linting, Styling, Testing and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - run: npm ci
      - run: npm run lint
      - run: npm run style
      - run: npm test
      - run: npm run build
